# Set minimum supported iOS version
platform :ios, '12.4'

target 'DailyDozen' do
  # Comment out the next line to *not*use* dynamic frameworks
  use_frameworks!

  # Pods for DailyDozen
  pod 'ActiveLabel', '~> 1.1.0'
  pod 'Charts', '~> 4.0.3'
  pod 'FSCalendar', '~> 2.8.4'
  pod 'RealmSwift', '~> 4.4.1'
  pod 'SimpleAnimation', '~> 0.4.2'

  target 'DailyDozenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DailyDozenUITests' do
    # Pods for testing
  end
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        # Exclude building for arm64 simulator (M1 chipset).
        # Apple XCFrameworks are needed to support this properly, future work.
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
        
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
                
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
        
        config.build_settings['SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD'] = 'NO'
        config.build_settings['SUPPORTS_MACCATALYST'] = 'NO'
        
        # not specified 'SWIFT_VERSION'
    end
  end
end
