# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
inhibit_all_warnings!

def common_pods
  ###########################
  ### Pods for DailyDozen ###
  ###########################
  
  ## https://cocoapods.org/pods/ActiveLabel
  ## https://github.com/optonaut/ActiveLabel.swift
  ## Swift: 5.0    
  ## Swift Package Manager: 4.2 :APPEARS_OK:
  pod 'ActiveLabel', '~> 1.1.0'
  
  ## https://cocoapods.org/pods/Charts
  ## https://github.com/danielgindi/Charts
  ## Swift: v5 ... 84% Swift, 15% ObjC, Swift demo code, ObjC demo code
  ## Swift Package Manager: 5.1
  pod 'Charts', '~> 3.5.0'
  
  ## https://cocoapods.org/pods/FSCalendar
  ## https://github.com/WenchaoD/FSCalendar
  ## Swift:   ... 88% ObjC
  ##          ... issues piling up (400+ open)
  ## Swift Package Manager: not supported
  pod 'FSCalendar', '~> 2.8.1'
  
  ## https://cocoapods.org/pods/RealmSwift
  ## https://github.com/realm/realm-cocoa
  ## Swift: looks like 5
  ## C++: cxx14
  ## Swift Package Manager: 5.0
  ## pod 'RealmSwift', '~> 3.18.0' ## Used in Daily Dozen release
  ## pod 'RealmSwift', '~> 3.21.0' ## Skipped
  pod 'RealmSwift', '~> 4.4.1'     ## 
  
  ## https://cocoapods.org/pods/SimpleAnimation
  ## https://github.com/keithito/SimpleAnimation
  ## Swift: 4.0 ... maybe ok at 4.2
  ## Swift Package Manager: unspecified
  pod 'SimpleAnimation', '~> 0.4.2'
end

target 'DailyDozen' do
  common_pods
end

target 'DailyDozenTests' do
  common_pods
end
