# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DailyDozen' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DailyDozen
  pod 'BmoViewPager', '~> 4.0'
  pod 'UICheckbox.Swift', '~> 1.0'

end
